### ISSUE TITLE
When glk::Splatting is drawn, wireframe is not drawn correctly

### ISSUE THREAD

**Issue by ymd-stella** [koide3/iridescence#95]
Related to https://github.com/koide3/iridescence/issues/92#issuecomment-2029586152

This disappearance seems to occur when Splatting is drawn.
In the following code, are glDisable and glEnable swapped?

https://github.com/koide3/iridescence/blob/ac17e6a3b0219e0653de73c683d1c5bdba5defa7/src/glk/splatting.cpp#L93-L107

**Comment by koide3** [comment]
Ah, thanks for finding it. That is the cause. It wrongly enables face culling after drawing splats. I also noticed that the same issue occured when rendering transparent objects due to a similar problem stems  from the face culling mode. I just pushed an update https://github.com/koide3/iridescence/pull/96/files that should fix the issue.
